clusterName: ""
environment: ""
region: ""
domain: ""

otelOperator:
  version: "0.119.0"

kubePrometheusStack:
  version: "68.4.4"
  grafanaAdminPassword: ""   # set via ExternalSecret in production

loki:
  version: "6.25.0"
  storageSize: 50Gi

kubernetesEventsExporter:
  version: "2.4.0"

noe:
  version: "0.15.0"

yace:
  version: "0.61.2"
