apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: {{ .Values.eso.version | quote }}
    helm:
      valuesObject:
        concurrent: {{ .Values.eso.concurrent }}
        extraArgs:
          client-burst: {{ .Values.eso.clientBurst | quote }}
          client-qps: {{ .Values.eso.clientQps | quote }}
          enable-secrets-caching: "true"
        resources:
          requests: { cpu: 100m, memory: 500Mi }
          limits:   { cpu: 500m, memory: 1Gi }
        tolerations:
          - key: system-node
            operator: Equal
            value: "true"
            effect: NoSchedule
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
